spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G3cjWS29GydMcaT49EV
      secret-key: mqaCRPEbnIVjG5u6G9LyWQm1QZRrxR
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: waibi
  application:
    name: waibi-third-party
server:
  port: 30000


